### ISSUE TITLE
Aggregate does not aggregate correctly

### ISSUE THREAD

**Issue by drt24** [mikioh/ipaddr#6]
Given the input:

    127.156.0.0/15
    127.159.0.0/16

Aggregate produces:

    127.156.0.0/14

But that includes the range 127.158.0.0/16 which is not in the input.

I also think there is an infinite loop somewhere with some inputs but I haven't managed to narrow down a test case yet.

**Comment by mikioh** [comment]
Thanks for the report, sorry for being late. I overlooked your report.
