### ISSUE TITLE
Aggregation incorrect with different seq of prefix

### ISSUE THREAD

**Issue by ldkingvivi** [mikioh/ipaddr#8]
Aggregation incorrect with different seq of prefix

results of {"8.8.8.0/25","8.8.8.128/25", "9.9.9.0/25"} is [8.8.8.0/24 9.9.9.0/25], which is correct
but if you change the seq of your input to {"8.8.8.0/25", "9.9.9.0/25","8.8.8.128/25"}, and result is [8.0.0.0/7] , which is wrong

**Comment by mikioh** [comment]
Thanks for the report. Yup, the function Aggregate doesn't take care with the input.
